version: "3"
x-airflow-common: &airflow-common
    build: .
    volumes:
        - ./setup/config/airflow.cfg:/opt/airflow/airflow.cfg
        - ./source/dags:/opt/airflow/dags
        - .:/application
        - ./source/requirements.txt:/requirements.txt
    env_file:
        - ./source/.env
    working_dir: /application

services:
    webserver:
        <<: *airflow-common
        command: bash -c "airflow db init && airflow webserver"
        ports:
            - 8080:8080

    scheduler:
        <<: *airflow-common
        command: scheduler

    worker:
        <<: *airflow-common
        command: celery worker

    postgres:
        image: postgres:9.6
        env_file:
            - ./source/.env
        volumes:
            - PGDATA:/var/lib/postgresql/data
    redis:
        image: redis:5.0.5

volumes:
    PGDATA:
